site_name: Blackwing Protocol
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
plugins:
  - mermaid2
nav:
  - Home: index.md
  - Mask: mask.md
  - Stamp: stamp.md
  - About: about.md